---
# inventory.ini の CatalystSW グループに定義されたIPアドレスを対象に、
# Ansible経由でCatalystへSSHログイン可能か事前確認を行う。
# 接続成功したホストは reachable_catalystsw グループへ動的追加する。
# 接続失敗したホストは unreachable_catalystsw グループへ動的追加する。
- name: CatalystSW HOST SSH PreCheck
  hosts: CatalystSW
  gather_facts: no

  tasks:

  # CatalystへSSH接続し、show clock コマンド実行可否を確認する。
  #
  # failed_when: false を指定することで、
  # SSH接続失敗時でもPlaybook全体を停止させず後続処理へ進める。
  #
  # changed_when: false を指定することで、
  # show clock を設定変更(change)扱いにしない。
  #
  # check_mode: false を指定することで、
  # ansible-playbook --check 実行時でも実際にSSH接続確認を行う。
 
  - name: Check Catalyst login
    cisco.ios.ios_command:
      commands:
        - show clock
    register: login_check
    failed_when: false
    changed_when: false
    check_mode: false

  # SSHログイン成功したホストを、
  # reachable_catalystsw という動的グループへ追加する。
  #
  # 後続Playではこのグループのみを対象に処理を行う。
  #
  # changed_when: false を指定することで、
  # inventory操作を change 扱いにしない。
  - name: Add reachable hosts
    ansible.builtin.add_host:
      name: "{{ inventory_hostname }}"
      groups: reachable_catalystsw
    when: not login_check.failed
    changed_when: false

  # SSHログイン失敗したホストを、
  # unreachable_catalystsw という動的グループへ追加する。
  #
  # 将来的にCSV出力や障害レポート生成へ利用可能。
  - name: Add unreachable hosts
    ansible.builtin.add_host:
      name: "{{ inventory_hostname }}"
      groups: unreachable_catalystsw
    when: login_check.failed
    changed_when: false

# reachable_catalystsw グループへ追加されたホストのみを対象に、
# バージョン情報取得などのPreCheck処理を実施する。
- name: Catalyst Status Check
  hosts: reachable_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
    # get_current_status role を呼び出す。
    - name: Import get_current_status role
      ansible.builtin.import_role:
        name: get_current_status
      tags: get_current_status


#ファームウェアバージョンがアップデートしたいファームウェアでないことを確認する
- name: 
  hosts: reachable_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
  # Check_Version role を呼び出す。
  - name: Import Check_IOS_Version role
    ansible.builtin.import_role:
      name: Check_IOS_Version
    tags: Check_IOS_Version

#ファームウェアバージョンがアップデートしたいファームウェアでないことを確認する
- name: 
  hosts: need_update_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
  # Check_Version role を呼び出す。
  #firmware_update_Catalyst1000 = Catalyst1000時のコマンド
  #firmware_update_installmode = Catalyst9000シリーズのコマンド
  - name: Import Check_IOS_Version role
    ansible.builtin.import_role:
      name: firmware_update_installmode
    tags: firmware_update_installmode