---
# reachable_catalystsw グループへ追加されたホストのみを対象に、
# バージョン情報取得などのPreCheck処理を実施する。
- name: SSH Connect PreCheck
  hosts: CatalystSW
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
    # get_current_status role を呼び出す。
    - name: SSH Connect PreCheck Task
      ansible.builtin.import_role:
        name: ssh_connect_precheck
      tags: ssh_connect_precheck

# reachable_catalystsw グループへ追加されたホストのみを対象に、
# バージョン情報取得などのPreCheck処理を実施する。
- name: Catalyst Status Check
  hosts: reachable_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
    # get_current_status role を呼び出す。
    - name: Import get_current_status role
      ansible.builtin.import_role:
        name: get_current_status
      tags: get_current_status


#ファームウェアバージョンがアップデートしたいファームウェアでないことを確認する
- name: 
  hosts: reachable_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
  # Check_Version role を呼び出す。
  - name: Import Check_IOS_Version role
    ansible.builtin.import_role:
      name: Check_IOS_Version
    tags: Check_IOS_Version

#ファームウェアバージョンがアップデートしたいファームウェアでないことを確認する
- name: 
  hosts: need_update_catalystsw
  gather_facts: no

  # Cisco IOS の enable モードへ自動遷移する。
  become: true
  become_method: enable

  tasks:
  # Check_Version role を呼び出す。
  #firmware_update_Catalyst1000 = Catalyst1000時のコマンド
  #firmware_update_installmode = Catalyst9000シリーズのコマンド
  - name: Import Check_IOS_Version role
    ansible.builtin.import_role:
      name: firmware_update_installmode
    tags: firmware_update_installmode