---
# !!重要!!バンドルモード(Catalyst1000シリーズ等)での実施手順
# TFTPサーバから firmware を flash へコピーする
- name: Upgrade Catalyst1000 IOS
  cisco.ios.ios_command:
    commands:
      - command: >-
          archive download-sw /overwrite /reload
          tftp://{{ tftp_server_ip }}/{{ target_ios_filename }}
  vars:
    ansible_command_timeout: 1800

  register: upgrade_result

# reload を実行する。
#
# reload後、
# SSH(22番) が復旧するまで待機する。
#
# Catalyst reboot は時間がかかるため
# timeout は長めに設定する。
- name: Wait for SSH recovery
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 60
    timeout: 1800
  delegate_to: localhost

# reboot後、
# show version を取得する。
- name: Get upgraded version
  cisco.ios.ios_command:
    commands:
      - "show version"
  register: upgraded_version
  retries: 10
  delay: 30
  until: upgraded_version is succeeded

# reboot後 version を表示する。
- name: Show upgraded version
  ansible.builtin.debug:
    var: upgraded_version.stdout_lines