---
# !!重要!!インストールモード(Catalyst9000シリーズ等)での実施手順
# TFTPサーバから firmware を flash へコピーする
- name: Copy firmware from TFTP server
  cisco.ios.ios_command:
    commands:
      - command: "copy tftp://{{ tftp_server_ip }}/{{ target_ios_filename }} flash:"
        prompt:
          - "Destination filename"
        answer:
          - "\r"
  vars:
    ansible_command_timeout: 1800
  register: copy_result

# dir flash: を実行し、firmwareファイルが存在するか確認する。
- name: Check firmware file exists
  cisco.ios.ios_command:
    commands:
      - "dir flash:"
  register: flash_result
  changed_when: false

# flash内に firmware file が存在するか判定する。
#
# 存在しない場合はTask失敗。
- name: Verify firmware file
  ansible.builtin.assert:
    that:
      - target_ios_filename in flash_result.stdout[0]
    success_msg: "Firmware file exists in flash"
    fail_msg: "Firmware file does not exist in flash"


# インストール・再起動前に保存を行う。
- name: Install firmware
  cisco.ios.ios_command:
    commands:
      - "write memory"

# install add file flash:xxx activate commit を実行する。
#
# install mode を使用する。
#
# activate:
#   次回boot imageへ設定
#
# commit:
#   boot変数へcommit
- name: Install firmware
  cisco.ios.ios_command:
    commands:
      - "install add file flash:{{ target_ios_filename }} activate commit"
  vars:
    ansible_command_timeout: 1800
    prompt:
      - "This operation may require a reload of the system. Do you want to proceed?"
    answer:
      - "y"
  register: install_result

# reload を実行する。
#
# reload後、
# SSH(22番) が復旧するまで待機する。
#
# Catalyst reboot は時間がかかるため
# timeout は長めに設定する。
- name: Wait for SSH recovery
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
    timeout: 900
  delegate_to: localhost

# reboot後、
# show version を取得する。
- name: Get upgraded version
  cisco.ios.ios_command:
    commands:
      - "show version"
  register: upgraded_version
  retries: 10
  delay: 30
  until: upgraded_version is succeeded

# reboot後 version を表示する。
- name: Show upgraded version
  ansible.builtin.debug:
    var: upgraded_version.stdout_lines

# 不要ファイルの削除
- name: Delete Old firmware
  cisco.ios.ios_command:
    commands:
      - "install remove inactive"
    prompt:
      - "Do you want to remove the above files?"
    answer:
      - "y"
  register: delete_firmware_result